language: python
sudo: required
python: 3.5
services:
- docker
env:
  matrix:
  - TOXENV=py35
  global:
    secure: Ox6kdTW/0M1+0buviy6HZh0S/JcACqIXiIzvJzsipvHdyShLcqx8jQ1cYPSTzuHlDIa9BV6N7IHdrQq5h2kup1+FgfMQ1fsSjMfiRdaBNir+jS0ql1siVDNtPjPugQKNAWSlXhLyJhEfwqs90ENgR5XiNn7vbC7+1z9J1SUf378HPxNmgSgwBXUenJ62UDX9I+S5Hbqle+rxOuoFvO6b0aJZxVCph9LPIboYop9dw+T1S1kU5/dkHE1ZmAaJojkdB9Yt5Qclv1WCFHWCcM1SjlXafr5rbAdCkiQ74X4Mxsu4PDfwbYBKruzxvJqOcpyvYiTu++PQxrfDr43Vng+sXd9ANi0UZobnibVOj+hv9gLfBCAgL1w7r3Y8LfiV5nQFSwqFBw5EpT4I/Suqgj7jE6Ee3wux1zHRR8SvpRx551dhCUX3ppVC2ouC72jaal8hejjayR8h1VtqdLtrNnHhckRt0lfDHIZVnoALwiiEfumJt5wRngYaMm9eY38lhQvGqB0Gyzvm/flKMnmJfHg4ix4PsxjhmOQhniavgkSeb17NzKgoTl0BX1pFYLfHEENVs6KDKZibFA3ta/USfmlhWjjoXH6K6XbV5DS4tM28UYQuPbB3y5ZaPtestzvhlhskukWhyuJ6QA9GYv8kFXz6raAJcygiBNjk4tdFj+lTtWE=
install:
- pip install -U tox
- pip install tox-travis
script:
- tox
